#!/bin/bash
for file in *.html; do
    if [ ! -e "../$file" ] || [ "$file" -nt "../$file" ]; then
        cp "$file" "../$file"
        echo "Copied: $file"
    else
        echo "Skipped: $file"
    fi
